---
- name: Installing Python MYSQL
  apt: name=python-mysqldb state=present
  sudo: yes

- name: Install mysql-server
  apt: name=mysql-server state=latest
  sudo: yes

- name: Update mysql root password for all root accounts
  mysql_user: name=root host={{item}} password={{ mysql_params.root_password }}
  sudo: yes
  with_items:
    - $ansible_hostname
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  sudo: yes

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{item}} state=absent
  sudo: yes
  with_items:
    - localhost
    - $inventory_hostname

- name: remove the test database
  mysql_db: name=test state=absent
  sudo: yes

- name: write conf.d/mysqld.cnf
  template: src=mysqld.cnf.j2 dest=/etc/mysql/conf.d/mysqld.cnf
  sudo: yes
  notify:
    - restart mysql

- name: write conf.d/client.cnf
  template: src=client.cnf.j2 dest=/etc/mysql/conf.d/client.cnf
  sudo: yes
  notify:
    - restart mysql